name: "Protokoll-Build"
description: "Run make, python and latexmk"
author: "kontakt@nicolaiweitkemper.de"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "file-text"
  color: "purple"
