name: Test workflow
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-build
      - uses: actions/upload-artifact@v2
        with:
            name: pdfs
            path: ./*/build/main.pdf
