name: Test workflow
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install…
        run: sudo apt-get install cmatrix
      - name: make_all
        run: ./make_all.sh
